services:
  - type: worker
    name: mossy-4x
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"
    envVars:
      - key: MODE
        value: demo
      - key: TZ
        value: Australia/Perth
      - key: HEARTBEAT_SECONDS
        value: "30"
      - key: DECISION_SECONDS
        value: "60"
      - key: OANDA_API_KEY
        sync: false
      - key: OANDA_ACCOUNT_ID
        sync: false
# ---------- MCP SERVICES ----------
  - type: web
    name: mcp-web
    env: docker
    plan: free
    dockerfilePath: mcp/Dockerfile
    autoDeploy: true
    envVars:
      - key: MCP_API_KEY
        sync: false
      - key: GH_PAT
        sync: false
      - key: RENDER_DEPLOY_HOOK_URL
        sync: false

  - type: cron               # ← exactly “cron”
    name: mcp-optimiser
    env: docker
    plan: starter
    dockerfilePath: mcp/Dockerfile
    command: >
      python optimiser.py && python patcher.py
    schedule: "0 1 * * *"
    envVars:
      - key: MCP_API_KEY
        sync: false
      - key: GH_PAT
        sync: false
      - key: RENDER_DEPLOY_HOOK_URL
        sync: false


        
  
