name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_NAME: ${{ secrets.RENDER_SERVICE_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install render-cli

      - name: Trigger Render deploy
        run: |
          if [ -z "${RENDER_API_KEY}" ] || [ -z "${RENDER_SERVICE_NAME}" ]; then
            echo "Render credentials are missing. Configure secrets first." >&2
            exit 1
          fi
          render login --api-key "${RENDER_API_KEY}"
          render services deploy "${RENDER_SERVICE_NAME}" --branch main --yes
