name: Finish Render Setup

on:
  workflow_dispatch:

jobs:
  run-finish-render-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run finish_render_setup.py
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          set -e
          python finish_render_setup.py

      - name: Success message
        if: success()
        run: echo "✅ Render services live and GitHub workflow dispatched."

      - name: Failure summary
        if: failure()
        run: |
          echo "finish_render_setup.py failed. Review logs for HTTP error details."
          exit 1
