name: self-audit-disabled

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Self-audit disabled
        run: echo "Mossy 4X self-audit is currently disabled."
